---
- name: Set PHP memory limit
  replace: dest={{ ezpublish_php_apache_ini_path }}/php.ini
           regexp='memory_limit =.*'
           replace='memory_limit = {{ ezpublish_php_memory_limit }}'
  notify: Restart Apache

- name: Set PHP max execution time
  replace: dest={{ ezpublish_php_apache_ini_path }}/php.ini
           regexp='max_execution_time =.*'
           replace='max_execution_time = {{ ezpublish_php_max_execution_time }}'
  notify: Restart Apache

- name: Set PHP timezone
  replace: dest={{ item }}/php.ini
           regexp=';date.timezone =.*'
           replace='date.timezone = {{ ezpublish_php_date_timezone }}'
  with_items:
    - "{{ ezpublish_php_apache_ini_path }}"
    - "{{ ezpublish_php_cli_ini_path }}"
  notify: Restart Apache

- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
