---
- name: Set APC shm_size
  lineinfile: dest=/etc/php5/conf.d/20-apc.ini
              line='apc.shm_size = {{ ezpublish_php_apc_shm_size }}'
  notify: Restart Apache

- name: Set Apache listen port
  replace: dest=/etc/{{ ezpublish_apache.daemon }}/ports.conf
           regexp='Listen 80'
           replace='Listen {{ ezpublish_apache_port }}'
  when: ezpublish_apache_port != 80
  notify: Restart Apache

- name: Set Apache listen port
  replace: dest=/etc/{{ ezpublish_apache.daemon }}/ports.conf
           regexp='NameVirtualHost *:80'
           replace='NameVirtualHost *:{{ ezpublish_apache_port }}'
  when: ezpublish_apache_port != 80
  notify: Restart Apache
