---
- name: Find PHP configuration file
  shell: find /etc -name 'php.ini'
  register: php_config_files
  changed_when: false

- name: Set PHP memory limit
  replace: dest={{ item }}
           regexp='memory_limit =.*'
           replace='memory_limit={{ ezpublish_php_memory_limit }}'
  with_items: php_config_files.stdout_lines
  notify: Restart Apache

- name: Set PHP max execution time
  replace: dest={{ item }}
           regexp='max_execution_time =.*'
           replace='max_execution_time={{ ezpublish_php_max_execution_time }}'
  with_items: php_config_files.stdout_lines
  notify: Restart Apache

- name: Set PHP timezone
  replace: dest={{ item }}
           regexp=';date.timezone =.*'
           replace='date.timezone = {{ ezpublish_php_date_timezone }}'
  with_items: php_config_files.stdout_lines
  notify: Restart Apache

- name: Set php session save handler
  replace: dest={{ item }}
           regexp='session.save_handler =.*'
           replace='session.save_handler={{ ezpublish_php_session_save_handler }}'
  with_items: php_config_files.stdout_lines
  when: ezpublish_php_session_save_handler|bool
  notify: Restart Apache

- name: Set php session save path
  replace: dest={{ item }}
           regexp=';session.save_path =.*'
           replace='session.save_path="{{ ezpublish_php_session_save_path }}"'
  with_items: php_config_files.stdout_lines
  when: ezpublish_php_session_save_path|bool
  notify: Restart Apache

- name: Find APC configuration file
  shell: find /etc -name 'apc.ini'
  register: apc_files
  changed_when: false

- name: Set APC shm_size
  lineinfile: dest={{ item }}
              line='apc.shm_size = {{ ezpublish_php_apc_shm_size }}'
  with_items: apc_files.stdout_lines
  notify: Restart Apache

- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
