---
- name: Create "{{ ezpublish_delivery_account }}" user
  user: name={{ ezpublish_delivery_account }} shell=/bin/bash comment="Delivery account" group={{ ezpublish_apache.group }} append=yes

- name: Create sudoers config for eZ Publish
  template: src=sudoers.j2 dest=/etc/sudoers.d/ezpublish mode=0755

- name: Authorizing ssh keys
  authorized_key: user={{ ezpublish_delivery_account }} key="{{ lookup('file', item ) }}"
  with_items: ezpublish_public_keys

- name: Make it owner of the project sources
  file: path={{ item.value.root }}
        owner={{ ezpublish_delivery_account }}
        group={{ ezpublish_apache.group }}
        state=directory
        mode=0755
        recurse=yes
  with_dict: ezpublish_apache_vhosts
