---
- name: RedHat | Install packages
  yum: name={{ item }}
       state=present
  with_items: ezpublish_packages

- name: RedHat | Install additional packages
  yum: name={{ item }}
       state=present
  with_items: ezpublish_additional_packages
  when: ezpublish_additional_packages|length > 0
