---
- name: Debian | Enable contrib and non-free software
  replace: dest=/etc/apt/sources.list
           regexp='main$'
           replace='main contrib non-free'

- name: Debian | Install packages
  apt: name={{ item }}
       state=present
       update_cache=yes
       cache_valid_time=3600
  with_items: ezpublish_packages

- name: Debian | Install apache modules
  apache2_module: name={{ item }}
                  state=present
  with_items: ezpublish_apache.mods_enabled
  notify: Restart Apache

- name: Debian | Add apache vhosts configuration.
  template:
    src: vhost_apache.conf.j2
    dest: "/etc/{{ ezpublish_apache.daemon }}/sites-available/{{ ezpublish_apache_vhost.filename }}"
  register: add_vhost

- name: Debian | Enable new vhost
  shell: a2ensite {{ ezpublish_apache_vhost.filename }}
  when: ezpublish_apache_vhost.enabled|bool and add_vhost.changed
  notify: Restart Apache

- name: Debian | Define a generic ServerName in default vhost
  lineinfile: dest="/etc/{{ ezpublish_apache.daemon }}/sites-available/default"
              line="        ServerName default"
              insertafter="ServerAdmin"
  notify: Restart Apache

