---
- name: Debian | Enable contrib and non-free software
  replace: dest=/etc/apt/sources.list
           regexp='main$'
           replace='main contrib non-free'

- name: Debian | Install packages
  apt: name={{ item }}
       state=present
       update_cache=yes
       cache_valid_time=3600
  with_items: ezpublish_packages

- name: Debian | Install additional packages
  apt: name={{ item }}
       state=present
       update_cache=yes
       cache_valid_time=3600
  with_items: ezpublish_additional_packages
  when: ezpublish_additional_packages|length > 0 

- name: Debian | Install apache modules
  apache2_module: name={{ item }}
                  state=present
  with_items: ezpublish_apache.mods_enabled
  notify: Restart Apache

- name: Debian | Define a generic ServerName in default vhost
  lineinfile: dest="/etc/{{ ezpublish_apache.daemon }}/sites-available/default"
              line="        ServerName default"
              insertafter="ServerAdmin"
  notify: Restart Apache

