---
# Web role tasks
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - ezpublish
    - always

- include: install.yml
  tags:
    - ezpublish
    - install

- include: configure.yml
  tags:
    - ezpublish
    - configure

- include: delivery-user.yml
  when: ezpublish_add_delivery_user
  tags:
    - ezpublish
    - delivery-user
