---
# Web role tasks
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - ezpublish
    - always

- include: install.yml
  tags:
    - ezpublish
    - install

- include: configure.yml
  tags:
    - ezpublish
    - configure

- include: download.yml
  tags:
    - ezpublish
    - download
  when: ezpublish_download|bool
