---
- name: Restart Apache
  service: name={{ ezpublish_apache.daemon }} state=restarted
  when: ezpublish_apache_started|bool

- name: Restart PHP-FPM
  service: name={{ ezpublish_fpm.daemon }} state=restarted
